Abdul/tk slot indexing
holaplex/solana-indexer pull request #267
Opened 2022-03-23 00:55 UTC by imabdulbasit

2022-03-23 18:07 UTC, kespinola reviewed
Looking good. Have some nested if statements maybe @ray-kast has some technics for handling.

2022-03-23 18:07 UTC, kespinola commented on crates/core/migrations/2022-03-22-214148_add_slot_col_and_trigger_to_token_account/up.sql
> +execute procedure trigger_set_updated_at_timestamp();
nice.

2022-03-24 19:32 UTC, ray-kast requested changes

2022-03-24 19:32 UTC, ray-kast commented on crates/indexer/src/accountsdb/accounts/token.rs
> +    }
```suggestion
    match rows.get(0).and_then(|r| r.slot) {
        Some(indexed_slot) if incoming_slot > indexed_slot => {
            client
                .db()
                .run(move |db| {
                    update(
                        token_accounts::table
                            .filter(token_accounts::address.eq(values.clone().address)),
                    )
                    .set(&values)
                    .execute(db)
                })
                .await
                .context("failed to update token account")?;
        },
        Some(_) => (),
        None => {
            client
                .db()
                .run(move |db| {
                    insert_into(token_accounts::table)
                        .values(&values)
                        .on_conflict_do_nothing()
                        .execute(db)
                })
                .await
                .context("failed to insert token account")?;
        },
    }
```

2022-03-24 19:37 UTC, ray-kast commented on crates/indexer/src/accountsdb/accounts/token.rs
> +                        .on_conflict_do_nothing()
may want this to be an `ON CONFLICT UPDATE`.  @imabdulbasit thoughts?

2022-03-24 19:50 UTC, merged